name: Build ant_cranelift_compiler

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            bin: antc
          - os: windows-latest
            bin: antc.exe
          - os: macos-latest
            bin: antc

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          gcc -c include/clib/arc.c -o include/clib/arc.o
          ar rcs include/clib/libarc.a include/clib/arc.o
          cargo build --release

      - name: Run tests
        run: |
          gcc -c include/clib/arc.c -o include/clib/arc.o
          ar rcs include/clib/libarc.a include/clib/arc.o
          cargo test --release

      - name: Inspect release output
        shell: bash
        run: ls -lah target/release

      - name: Package Artifacts
        shell: bash
        run: |
          mkdir staging
          cp target/release/${{ matrix.bin }} staging/
          cp -r include staging/
          cp -r std staging/
          
          if [ "${{ runner.os }}" == "Windows" ]; then
            7z a antc-${{ matrix.os }}.zip ./staging/*
          else
            cd staging && zip -r ../antc-${{ matrix.os }}.zip ./* && cd ..
          fi

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          # 下载时的文件名
          name: antc-${{ matrix.os }}-package
          # 需要上传的 zip 文件路径
          path: antc-${{ matrix.os }}.zip